sequenceDiagram
  actor p0 as User
  participant p1 as Client
  participant p2 as Server
  p0->>p1: Log in
  p1->>+p2: Credentials
  p2-->>-p1: Session token
  p1-)p2: Analytics
  p1--xp0: Expired
  p1<<->>p2: Keepalive
  p1->p1: Store token
