sequenceDiagram
  actor U as User
  participant C as Client
  participant S as Server
  U->>C: Log in
  C->>+S: Credentials
  S-->>-C: Session token
  C-)S: Analytics
  C--xU: Expired
  C<<->>S: Keepalive
  C->C: Store token
  %% a comment
